### PR TITLE
Add `inspect-flags` to pass additional options to `k6 inspect`

### PR DESCRIPTION
**Pull request by dh-alexm**
This PR adds the optional action parameter `inspect-flags` following the same pattern that the existing `flags` parameter uses. Our primary use case for this change is to make sure we can pass the [Typescript Compatibility Mode](https://grafana.com/docs/k6/latest/using-k6/javascript-typescript-compatibility-mode/#javascript-and-typescript-compatibility-mode) flag (`--compatibility-mode=experimental_enhanced`) to both `k6 run` and `k6 inspect`

### CODE REVIEW

**Comment by DefCon-007** [comment]
@dh-alexm Thanks a lot for contributing this change. I am not sure if there are any `inspect` specific flags available to use. Would it make sense to pass the values from `flags` input to the inspect command as well?

**Comment by dh-alexm** [comment]
Because the two commands (`run` and `inspect`) take different options, it's not possible to use the same set of flags for both commands without doing some processing to ensure unknown flags aren't passed to the incorrect command. For example `k6 inspect --vus 10` will fail with an `unknown flag: --vus` error.

I briefly weighed not exposing the options for inspect and taking an approach of making `compatibility-mode` a parameter that would be set on both commands. Alternatively, it'd be possible to check the passed in `flags` for `compatibility-mode` and pass just that option to `inspect` if it's provided.

Happy to accommodate any approach that feels like it makes sense!

**Comment by DefCon-007** [comment]
Maybe I should have phrased it better. `run` and `inspect` cannot be executed simultaneously in the same step i.e. if you keep `only-verify-scripts` as true, the action will execute `inspect` command, otherwise, it will execute the `run` command. Because of this, I think it will be simpler to keep a single input for flags for both of the cases.

**Comment by dh-alexm** [comment]
My understanding is that the action will run `inspect` in all cases, triggered by the internals of [this call](https://github.com/grafana/run-k6-action/blob/167b75d4534b2228c0ecdfeae014debce2c118c7/src/index.ts#L41).

After the `inspect` succeeds, if `only-verify-scripts` is true the action exits. If it is false, then the script proceeds to execute `run`.

**Review by DefCon-007 — APPROVED** [review]

**Comment by DefCon-007** [comment]
Ah! My bad, this was added later. Makes sense. I have approved the PR. Could you update the readme as well with the new input before merging?

**Comment by dh-alexm** [comment]
No worries!

I've added the new input to the readme and a small example of using Typescript in the "Advanced" section.

**Pull request merged**
